@startuml
skinparam style strictuml

package javax.lang.model {
    interface Element {
        + getKind(): ElementKind
        + getModifiers(): Set<Modifier>
        + getSimpleName(): Name
        + getEnclosingElement(): Element
        + asType(): TypeMirror
        + getEnclosedElements(): List<? extends Element>

    }
    interface TypeMirror {
        + getKind(): TypeKind
        + toString(): String
    }

    interface TypeElement extends Element {
        + getQualifiedName(): Name
        + getInterfaces(): List<? extends TypeMirror>
        + getSuperclass(): TypeMirror
        + getTypeParameters(): List<? extends TypeParameterElement>
        + getEnclosingElement(): Element
        + getSimpleName(): Name
        + getEnclosedElements(): List<? extends Element>
    }
    interface TypeParameterElement extends Element {
        + getBounds(): List<? extends TypeMirror>
        + getGenericElement(): Element
        + getSimpleName(): Name
    }

    enum ElementKind {
        ANNOTATION_TYPE,
        CLASS,
        ENUM,
        ENUM_CONSTANT,
        FIELD,
        INTERFACE,
        LOCAL_VARIABLE,
        METHOD,
        PACKAGE,
        PARAMETER,
        TYPE_PARAMETER,
        OTHER,
        RESOURCE_VARIABLE
    }
    enum Modifier {
        ABSTRACT,
        DEFAULT,
        FINAL,
        NATIVE,
        PRIVATE,
        PROTECTED,
        PUBLIC,
        STATIC,
        STRICTFP,
        SYNCHRONIZED,
        TRANSIENT,
        VOLATILE
    }
    interface TypeKind {
        BOOLEAN,
        BYTE,
        CHAR,
        DOUBLE,
        FLOAT,
        INT,
        LONG,
        SHORT,
        VOID,
        DECLARED,
        ARRAY,
        ERROR,
        TYPEVAR,
        WILDCARD,
        PACKAGE
    }


@enduml