@startuml
    'https://plantuml.com/sequence-diagram
    skinparam style strictuml

    participant "Java2Puml.class" as Main
    participant "ToolProvider.class" as ToolProvider
    participant "toolProvider : ToolProvider" as toolProvider
    participant Doclet
    participant Doclet.Options
    participant SourceVersion
    participant "docletEnvironment : DocletEnvironment" as DocletEnvironment

    autonumber
    [-> Main : main(args)
    Main -> ToolProvider ++: findFirst("javadoc").get()
    ToolProvider --> Main --: toolProvider

    ToolProvider -> toolProvider ++ : run()

    toolProvider -->> Doclet : <<Create>> Doclet()
    toolProvider -> Doclet.Options ++ : getSupportedOptions()
    Doclet.Options --> toolProvider --: supported options


    toolProvider -> SourceVersion ++: getSuportedSourceVersion()
    SourceVersion --> toolProvider --: SourceVersion

    toolProvider -> Doclet ++ : run()
    Doclet -->>  DocletEnvironment : <<Create>> docletEnvironment()
    DocletEnvironment --> toolProvider --: true on success
    @enduml
