@startuml
skinparam style strictuml
skinparam classFontStyle Bold
skinparam classAttributeIconSize 0
package western{
class Boisson { 
  - substantif
  +{static} EAU
  -{static} boissons
  +{static} of(nom : String genre : Genre ) : Boisson
  - <<create>> Boisson(nom : String genre : Genre ) 
  + getNom() : String
  + getGenre() : Genre
  + getNomAvecArticleIndefini() : String
  + getNomAvecArticlePartitif() : String
  + getNomAvecArticleDefini() : String
  + getNomAvecPreposition(preposition : String ) : String
}

class Brigand { 
  #{static} LOOK_PAR_DEFAUT
  - look
  - recompense
  - estLibre
  - captives
  - gardien
  + <<create>> Brigand(nom : String ) 
  + <<create>> Brigand(nom : String boisson : Boisson ) 
  + <<create>> Brigand(nom : String boisson : Boisson look : String ) 
  + getLook() : String
  + getRecompense() Integer
  + estLibre() Boolean
  + kidnapper(dame : Dame ) 
  + getCaptives() : List
  + seFaireCapturer(cowBoy : Cowboy ) 
  + seFaireTirerDessus(cowBoy : Cowboy ) 
  + getPseudo() : String
  + sePresenter() 
  -{static} boissonParDefaut
  +{static} getBoissonParDefaut() : Boisson
  +{static} setBoissonParDefaut(boisson : Boisson ) 
}

class Cowboy { 
  - gains
  - captures
  + <<create>> Cowboy(nom : String ) 
  + <<create>> Cowboy(nom : String boisson : Boisson ) 
  + getPseudo() : String
  + liberer(dame : Dame ) 
  + liberer(captives : List ) 
  + capturer(horsLaLoi : HorsLaLoi ) 
  + tirerSur(brigand : HorsLaLoi ) 
  + sePresenter() 
  -{static} boissonParDefaut
  +{static} getBoissonParDefaut() : Boisson
  +{static} setBoissonParDefaut(boisson : Boisson ) 
}

class Dame { 
  - estLibre
  - sauveur
  - ravisseur
  + <<create>> Dame(nom : String ) 
  + <<create>> Dame(nom : String boisson : Boisson ) 
  + getPseudo() : String
  + seFaireKidnapper(horsLaLoi : HorsLaLoi ) 
  + seFaireLiberer(cowBoy : Cowboy ) 
  + estLibre() Boolean
  + sePresenter() 
  -{static} boissonParDefaut
  +{static} getBoissonParDefaut() : Boisson
  +{static} setBoissonParDefaut(boisson : Boisson ) 
  + getRavisseur() : HorsLaLoi
}

class Histoire4 { 
  + <<create>> Histoire4() 
  +{static} main(args : String ) 
}

class Narrateur { 
  + <<create>> Narrateur() 
  + <<create>> Narrateur(nom : String ) 
  + dire(texte : String ) 
  + boire(boisson : Boisson ) 
  + boire() 
  + getPseudo() : String
}

class Personnage { 
  -{static} BOISSON_PAR_DEFAUT
  - nom
  - boisson
  + <<create>> Personnage(nom : String ) 
  + <<create>> Personnage(nom : String boisson : Boisson ) 
  + dire(texte : String ) 
  + sePresenter() 
  + boire(boisson : Boisson ) 
  + boire() 
  + getNom() : String
  + getBoisson() : Boisson
  +{static} getPseudos(personnages : List ) : String
  +{static} getBoissonParDefaut() : Boisson
}

class Ripou { 
  - brigand
  + <<create>> Ripou(nom : String ) 
  + <<create>> Ripou(nom : String boisson : Boisson ) 
  + <<create>> Ripou(nom : String boisson : Boisson look : String ) 
  + getLook() : String
  + estLibre() Boolean
  + getRecompense() Integer
  + kidnapper(dame : Dame ) 
  + getCaptives() : List
  + seFaireCapturer(cowBoy : Cowboy ) 
  + seFaireTirerDessus(cowBoy : Cowboy ) 
  + getPseudo() : String
  + sePresenter() 
  + liberer(dame : Dame ) 
}

class Sherif { 
  - cowboy
  - wanted
  + <<create>> Sherif(nom : String ) 
  + <<create>> Sherif(nom : String boisson : Boisson ) 
  + getNom() : String
  + sePresenter() 
  + capturer(horsLaLoi : HorsLaLoi ) 
  + getWanted() : List
  + rechercher(horsLaLoi : HorsLaLoi ) 
  + isWanted(horsLaLoi : HorsLaLoi ) : Boolean
}

class Substantif { 
  - nom
  - genre
  + <<create>> Substantif(nom : String genre : Genre ) 
  + getNom() : String
  + getGenre() : Genre
  + toString() : String
  +{static} isVowel() Boolean
  +{static} startsWithVowel(s : String ) Boolean
  + getArticleIndefini() : String
  + avecArticleIndefini() : String
  +{static} getArticleDefini(genre : Genre ) : String
  + getArticleDefini() : String
  + avecArticleDefini() : String
  +{static} faireElision(article : String ) : String
  + elision() Boolean
  + getArticlePartitif() : String
  + avecArticlePartitif() : String
  + avecElision(article : String ) : String
  + avecPreposition(preposition : String ) : String
}

interface HorsLaLoi <<interface>> {
  +  estLibre() Boolean
  +  getRecompense() Integer
  +  kidnapper(dame : Dame ) 
  +  seFaireCapturer(cowBoy : Cowboy ) 
  +  seFaireTirerDessus(cowBoy : Cowboy ) 
  +  getLook() : String
  +  getCaptives() : List
}

interface Nommable <<interface>> {
  +  getNom() : String
  +  getPseudo() : String
}

enum Genre <<enumerate>> {
  +{static} FEMININ
  +{static} MASCULIN
}

}
@enduml
