@startuml
skinparam style strictuml
skinparam classFontStyle Bold
skinparam classAttributeIconSize 0
package western{
class western.Boisson {
}

class western.Brigand {
LOOK_PAR_DEFAUT
look
recompense
estLibre
}

class western.Cowboy {
gains
}

class western.Dame {
estLibre
}

class western.Histoire4 {
}

class western.Narrateur {
}

class western.Personnage {
nom
}

class western.Ripou {
}

class western.Sherif {
}

class western.Substantif {
nom
}

interface western.HorsLaLoi <<interface>> {
}

interface western.Nommable <<interface>> {
}

enum western.Genre <<enumerate>> {
FEMININ
MASCULIN
}

western.HorsLaLoi <|.. western.Brigand
western.Nommable <|.. western.Personnage
western.HorsLaLoi <|.. western.Ripou
western.Personnage <|-- western.Brigand
western.Personnage <|-- western.Cowboy
western.Personnage <|-- western.Dame
western.Personnage <|-- western.Narrateur
western.Cowboy <|-- western.Ripou
western.Cowboy <|-- western.Sherif
western.Boisson -- western.Substantif
western.Boisson -- western.Boisson
western.Brigand -- western.Cowboy
western.Brigand -- western.Boisson
western.Cowboy -- western.Boisson
western.Dame -- western.Cowboy
western.Dame -- western.HorsLaLoi
western.Dame -- western.Boisson
western.Personnage -- western.Boisson
western.Personnage -- western.Boisson
western.Ripou -- western.Brigand
western.Sherif -- western.Cowboy
western.Substantif -- western.Genre
}
@enduml
