@startuml
skinparam style strictuml
skinparam classFontStyle Bold
skinparam classAttributeIconSize 0
package western{
class Boisson {
}

class Brigand {
LOOK_PAR_DEFAUT
look
recompense
estLibre
}

class Cowboy {
gains
}

class Dame {
estLibre
}

class Histoire4 {
}

class Narrateur {
}

class Personnage {
nom
}

class Ripou {
}

class Sherif {
}

class Substantif {
nom
}

interface HorsLaLoi <<interface>> {
}

interface Nommable <<interface>> {
}

enum Genre <<enumerate>> {
FEMININ
MASCULIN
}

}
@enduml
